# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Handover < Formula
  desc "Repo-local handover orchestration for coding agents"
  homepage "https://handover.openusage.sh/"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/janekbaraniewski/handover/releases/download/v0.1.3/handover_0.1.3_darwin_x86_64.tar.gz"
      sha256 "504f90360e4f96d6a7512c2ece22de22c0935cb3b1cda9beab48f875025db992"

      define_method(:install) do
        bin.install "handover"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/janekbaraniewski/handover/releases/download/v0.1.3/handover_0.1.3_darwin_arm64.tar.gz"
      sha256 "fe2bbcdff31a03ef4f27fad3a19cf27efb81c6c7f1659c6a6a70fa3691392c17"

      define_method(:install) do
        bin.install "handover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/janekbaraniewski/handover/releases/download/v0.1.3/handover_0.1.3_linux_x86_64.tar.gz"
      sha256 "a64f355e8d62674c7b7cbbc0b30b0c3848e0a765161945c6ad33d914769d1b85"
      define_method(:install) do
        bin.install "handover"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/janekbaraniewski/handover/releases/download/v0.1.3/handover_0.1.3_linux_arm64.tar.gz"
      sha256 "79c633ebc730711024f75c07382e9c33a7395f9088766111935cf27965265d3a"
      define_method(:install) do
        bin.install "handover"
      end
    end
  end

  test do
    system "#{bin}/handover", "--help"
  end
end
