# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Handover < Formula
  desc "Repo-local handover orchestration for coding agents"
  homepage "https://handover.openusage.sh/"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/janekbaraniewski/handover/releases/download/v0.1.1/handover_0.1.1_darwin_x86_64.tar.gz"
      sha256 "f2ccc99e6ed379dffa1f6b9f1b9bea5305210fc0244d13973fe91da1da3324c2"

      define_method(:install) do
        bin.install "handover"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/janekbaraniewski/handover/releases/download/v0.1.1/handover_0.1.1_darwin_arm64.tar.gz"
      sha256 "e477d11f6e9d0631ab0005a277ff2928c37935151d0bbca649b1d2b6e22aee0e"

      define_method(:install) do
        bin.install "handover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/janekbaraniewski/handover/releases/download/v0.1.1/handover_0.1.1_linux_x86_64.tar.gz"
      sha256 "2301fbc7493549d56bd566a0cc68bd0962cf6624dc7bca412bad06874c269208"
      define_method(:install) do
        bin.install "handover"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/janekbaraniewski/handover/releases/download/v0.1.1/handover_0.1.1_linux_arm64.tar.gz"
      sha256 "a7b8bf45b5c36c409399a3dcd3af9da953cdfddccdc3185089ff75178921eeb0"
      define_method(:install) do
        bin.install "handover"
      end
    end
  end

  test do
    system "#{bin}/handover", "--help"
  end
end
